//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASLMonthlyCapitalExpenditureStatement.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\user\\source\\repos\\Projects\\C# Programming Projects\\My Projects\\MASL Mont" +
            "hly Capital Expenditure Statement\\MASLMonthlyCapitalExpenditureStatement\\Monthly" +
            "CapitalExpenditureStatementSystemDB.mdf")]
        public string DatabaseLocation {
            get {
                return ((string)(this["DatabaseLocation"]));
            }
            set {
                this["DatabaseLocation"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\MonthlyCapita" +
            "lExpenditureStatementSystemDB.mdf;Integrated Security=True")]
        public string MonthlyCapitalExpenditureStatementSystemDBConnectionString {
            get {
                return ((string)(this["MonthlyCapitalExpenditureStatementSystemDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Forms.Form LoginScreen {
            get {
                return ((global::System.Windows.Forms.Form)(this["LoginScreen"]));
            }
            set {
                this["LoginScreen"] = value;
            }
        }
    }
}
